language: java
cache:
  directories:
  - $HOME/.gradle/caches/modules-2/
  - $HOME/.gradle/wrapper/
  - $HOME/.m2/
  - plugin-maven/build/localMavenRepository/
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr plugin-maven/build/localMavenRepository/com/diffplug/spotless/  
env:
  - NODE_VERSION="6.10.2"
before_install:
  - nvm install $NODE_VERSION
install: true
jdk:
  - openjdk8
  - openjdk11

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script: ./gradlew build --build-cache && ./gradlew npmTest --build-cache

    - stage: test
      jdk: openjdk11
      script: ./gradlew build --build-cache && ./gradlew npmTest --build-cache
