anchors:
  env_gradle: &env_gradle
    parallelism: 2
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

  restore_cache_wrapper: &restore_cache_wrapper
    restore_cache:
      key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  restore_cache_deps: &restore_cache_deps
    restore_cache:
      keys:
        - gradle-deps-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
        - gradle-deps-

version: 2
jobs:
  # gradlew spotlessCheck assemble testClasses
  assemble_testClasses: 
    <<: *env_gradle
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - *restore_cache_wrapper
      - *restore_cache_deps
      - run:
          name: gradlew spotlessCheck assemble testClasses
          command: ./gradlew spotlessCheck assemble testClasses --build-cache
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-deps-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
  # JRE8: export SPOTLESS_EXCLUDE_MAVEN=true && ./gradlew check
  test_nomaven_8:
    <<: *env_gradle
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - *restore_cache_wrapper
      - *restore_cache_deps
      - run:
          name: gradlew check
          command: export SPOTLESS_EXCLUDE_MAVEN=true && ./gradlew check --build-cache
      - store_test_results:
          path: plugin-gradle/build/test-results/test
  # JRE8: gradlew :plugin-maven:check
  test_justmaven_8:
    << : *env_gradle
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - *restore_cache_wrapper
      - *restore_cache_deps
      - run:
          name: gradlew :plugin-maven:check
          command: ./gradlew :plugin-maven:check --build-cache
      - store_test_results:
          path: plugin-maven/build/test-results/test
      - store_test_results:
          path: plugin-maven/build/spotbugs
      - store_artifacts:
          path: plugin-maven/build/test-results/test
      - store_artifacts:
          path: plugin-maven/build/spotbugs
workflows:
  version: 2
  assemble_and_test:
    jobs:
      - assemble_testClasses
      - test_justmaven_8:
        requires:
          - assemble_testClasses
      - test_nomaven_8:
          requires:
            - assemble_testClasses
